name: quranku
description: "QuranKu - Al-Quran, terjemahan, murotal, dan jadwal sholat."
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  http: ^1.6.0
  shared_preferences: 2.2.3
  shared_preferences_android: 2.2.4
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.3.2
  flutter_local_notifications: ^20.0.0
  permission_handler: ^12.0.1
  intl: ^0.20.2
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.12
  dio: ^5.9.1
  path_provider: ^2.1.5
  home_widget: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_with_background.png"
  min_sdk_android: 21
  adaptive_icon_background: "#F4F9F9"
  adaptive_icon_foreground: "assets/foreground_padded.png"

flutter:
  uses-material-design: true
  assets:
    - assets/editions.json
    - assets/loc_indonesian.json
    - assets/surah_list.json
    - assets/splash.png
